version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-type: direct # Dependencies explicitly defined in the Cargo.toml file
      - dependency-type: indirect # Dependencies implicitly defined in the Cargo.lock file
    ignore:
      # Do not update wgpu dependencies, it's a transient dependency from egui that is currently defined in the Cargo.toml file to override the default features.
      # But the version should still be managed by egui
      - dependency-name: "wgpu*"
    groups:
      cargo:
        patterns:
          - "*"
